import type { Metadata } from "next";
import React from "react";




export const metadata: Metadata = {
    title: "Auth",
    description: "Generated by create next app",
}

export default function RootLayout({
    children
}: Readonly<
    { children: React.ReactNode }
>
) {
    return (
        <html lang="en">
            <body
                className={`font-mono`}
            >
                <h1>Hi BABY</h1>
                {children}
            </body>
        </html>
    )
}